<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerL1q14xz\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerL1q14xz/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerL1q14xz.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerL1q14xz\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerL1q14xz\srcApp_KernelProdContainer([
    'container.build_hash' => 'L1q14xz',
    'container.build_id' => '2109265e',
    'container.build_time' => 1611323741,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerL1q14xz');
