<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerY1C3x22\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerY1C3x22/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerY1C3x22.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerY1C3x22\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerY1C3x22\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Y1C3x22',
    'container.build_id' => 'c3ccf824',
    'container.build_time' => 1611652318,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerY1C3x22');
